# Generated by Django 5.1.3 on 2024-12-16 14:23

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedScheduleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('instance_id', models.CharField(max_length=255)),
                ('instance_name', models.CharField(max_length=255)),
                ('schedule_created_at', models.DateTimeField()),
                ('weekly_day', models.CharField(blank=True, max_length=9, null=True)),
                ('weekly_start', models.TimeField(blank=True, null=True)),
                ('weekly_end', models.TimeField(blank=True, null=True)),
                ('monthly_day', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_start', models.TimeField(blank=True, null=True)),
                ('monthly_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'combined_schedule_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AWSCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenancy_ocid', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('user_ocid', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('fingerprint', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('private_key', django_cryptography.fields.encrypt(models.TextField())),
                ('region', django_cryptography.fields.encrypt(models.CharField(default='sa-vinhedo-1', max_length=50))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20)),
                ('week_days', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_time', models.TimeField(blank=True, null=True)),
                ('time_option', models.CharField(blank=True, max_length=20, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('occurrence', models.CharField(blank=True, max_length=20, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('calendar_day', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.PositiveIntegerField()),
                ('time_interval_start', models.TimeField()),
                ('time_interval_end', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='api_rest.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='UserCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_type', models.CharField(choices=[('OCI', 'Oracle Cloud Infrastructure'), ('AWS', 'Amazon Web Services'), ('Azure', 'Microsoft Azure')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('cpu_count', models.IntegerField()),
                ('memory_gb', models.FloatField()),
                ('lifecycle_state', models.CharField(max_length=50)),
                ('compartment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='api_rest.usercloud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('time_interval_start', models.TimeField()),
                ('time_interval_end', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='api_rest.schedule')),
            ],
        ),
    ]
