# Generated by Django 5.1.3 on 2024-11-13 03:05

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='cloud_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cloud_provider',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='user',
        ),
        migrations.CreateModel(
            name='OCICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenancy_ocid', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('user_ocid', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('fingerprint', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('private_key', django_cryptography.fields.encrypt(models.TextField())),
                ('compartment_id', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CloudProvider',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VirtualMachine',
        ),
    ]
