# Generated by Django 5.1.3 on 2024-11-25 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_vm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20)),
                ('week_days', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_time', models.TimeField(blank=True, null=True)),
                ('time_option', models.CharField(blank=True, max_length=20, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('occurrence', models.CharField(blank=True, max_length=20, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('calendar_day', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
