# Generated by Django 5.1.3 on 2024-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_intervalschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceschedule',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
