# Generated by Django 5.1.3 on 2024-12-10 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_intervalschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedScheduleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('instance_id', models.IntegerField()),
                ('instance_name', models.CharField(max_length=255)),
                ('next_execution', models.DateTimeField()),
                ('schedule_created_at', models.DateTimeField()),
                ('weekly_day', models.CharField(blank=True, max_length=9, null=True)),
                ('weekly_start', models.TimeField(blank=True, null=True)),
                ('weekly_end', models.TimeField(blank=True, null=True)),
                ('monthly_day', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_start', models.TimeField(blank=True, null=True)),
                ('monthly_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'combined_schedule_view',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='intervalschedule',
            name='user',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255)),
                ('next_execution', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.PositiveIntegerField()),
                ('time_interval_start', models.TimeField()),
                ('time_interval_end', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='api_rest.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('time_interval_start', models.TimeField()),
                ('time_interval_end', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='api_rest.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='InstanceSchedule',
        ),
        migrations.DeleteModel(
            name='IntervalSchedule',
        ),
    ]
