# Generated by Django 5.1.3 on 2024-12-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_combinedscheduleview_remove_intervalschedule_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='next_execution',
        ),
    ]
